version: '3.7'
services:
  postgres:
    container_name: strapi_psql
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}